// ===== VANFLIX DATA =====
export const movies = [
  {
    id: 1,
    title: "Dark Matter",
    genre: ["Sci-Fi", "Thriller"],
    year: 2025,
    rating: 8.6,
    match: 97,
    duration: "2h 18m",
    description: "Un astronauta queda atrapado en la órbita de un agujero negro que desafía las leyes de la física. Mientras la tripulación lucha por sobrevivir, descubren que el universo guarda secretos que la humanidad no debería conocer.",
    cast: "John Boyega, Florence Pugh, Lance Reddick",
    poster: "/poster1.jpg",
    backdrop: "/hero.jpg",
    badge: "NUEVO",
    featured: true,
  },
  {
    id: 2,
    title: "Iron Ghost",
    genre: ["Acción", "Thriller"],
    year: 2025,
    rating: 7.9,
    match: 94,
    duration: "2h 04m",
    description: "Un soldado de operaciones especiales con exoesqueleto de última generación debe detener una conspiración militar que amenaza con desatar una guerra mundial. Solo. En 24 horas.",
    cast: "Idris Elba, Ana de Armas, Oscar Isaac",
    poster: "/poster2.jpg",
    backdrop: "/hero.jpg",
    badge: "EXCLUSIVO",
    featured: false,
  },
  {
    id: 3,
    title: "Throne of Ash",
    genre: ["Fantasía", "Drama"],
    year: 2024,
    rating: 9.1,
    match: 99,
    duration: "2h 47m",
    description: "En un reino donde los dragones son dioses y los reyes meros mortales, una heredera maldita debe forjar una alianza imposible antes de que el fuego consuma todo lo que ama.",
    cast: "Anya Taylor-Joy, Henry Cavill, Cate Blanchett",
    poster: "/poster3.jpg",
    backdrop: "/hero.jpg",
    badge: "TOP 1",
    featured: false,
  },
  {
    id: 4,
    title: "Neon Syndicate",
    genre: ["Crimen", "Cyberpunk"],
    year: 2025,
    rating: 8.2,
    match: 92,
    duration: "1h 58m",
    description: "En Neo-Kyoto 2084, una detective corporativa infiltrada en el sindicato más peligroso de la ciudad descubre que la conspiración llega más alto de lo que imaginaba.",
    cast: "Michelle Yeoh, Jake Gyllenhaal, Zendaya",
    poster: "/poster1.jpg",
    backdrop: "/hero.jpg",
    badge: null,
    featured: false,
  },
  {
    id: 5,
    title: "Silent Abyss",
    genre: ["Horror", "Thriller"],
    year: 2024,
    rating: 7.4,
    match: 88,
    duration: "1h 42m",
    description: "Una expedición científica en las profundidades del Pacífico activa algo que no debería haber sido despertado. El sonido ya no es su aliado, el silencio es lo único que los mantiene vivos.",
    cast: "Lupita Nyong'o, Timothée Chalamet, Florence Pugh",
    poster: "/poster2.jpg",
    backdrop: "/hero.jpg",
    badge: null,
    featured: false,
  },
  {
    id: 6,
    title: "Crimson Protocol",
    genre: ["Espionaje", "Acción"],
    year: 2025,
    rating: 8.0,
    match: 95,
    duration: "2h 12m",
    description: "Una agente de inteligencia con doble identidad debe elegir entre su lealtad a su país o salvar a millones de civiles. El tiempo se acaba y nadie es quien dice ser.",
    cast: "Charlize Theron, Michael B. Jordan, Tom Hardy",
    poster: "/poster3.jpg",
    backdrop: "/hero.jpg",
    badge: "ESTRENO",
    featured: false,
  },
  {
    id: 7,
    title: "The Last Signal",
    genre: ["Sci-Fi", "Drama"],
    year: 2024,
    rating: 8.8,
    match: 96,
    duration: "2h 31m",
    description: "La última transmisión desde una colonia espacial perdida contiene un mensaje que podría cambiar la comprensión de la humanidad sobre el cosmos. Pero alguien no quiere que sea descifrado.",
    cast: "Ryan Gosling, Jodie Comer, Daniel Kaluuya",
    poster: "/poster1.jpg",
    backdrop: "/hero.jpg",
    badge: null,
    featured: false,
  },
  {
    id: 8,
    title: "Hollow Crown",
    genre: ["Drama", "Historia"],
    year: 2024,
    rating: 8.5,
    match: 91,
    duration: "3h 02m",
    description: "La caída de un impero narrada desde los ojos de sus siervos. Una épica que redefine cómo el poder corrompe y cómo la resistencia nace en los lugares más inesperados.",
    cast: "Cate Blanchett, Denzel Washington, Saoirse Ronan",
    poster: "/poster2.jpg",
    backdrop: "/hero.jpg",
    badge: "PREMIADA",
    featured: false,
  },
  {
    id: 9,
    title: "Vector Zero",
    genre: ["Acción", "Sci-Fi"],
    year: 2025,
    rating: 7.7,
    match: 89,
    duration: "1h 55m",
    description: "Un piloto experimental descubre que su avión de pruebas puede viajar a dimensiones paralelas. Cada vuelo lo aleja más de su realidad y más cerca de un punto sin retorno.",
    cast: "Tom Cruise, Margot Robbie, Pedro Pascal",
    poster: "/poster3.jpg",
    backdrop: "/hero.jpg",
    badge: null,
    featured: false,
  },
  {
    id: 10,
    title: "Obsidian Queen",
    genre: ["Fantasía", "Acción"],
    year: 2025,
    rating: 8.3,
    match: 93,
    duration: "2h 19m",
    description: "Una guerrera que nació de la ceniza de un volcán sagrado debe reclamar su trono de la oscuridad antes de que el sol se apague para siempre en su mundo.",
    cast: "Lupita Nyong'o, Mahershala Ali, Naomie Harris",
    poster: "/poster1.jpg",
    backdrop: "/hero.jpg",
    badge: "VANFLIX ORIGINAL",
    featured: false,
  },
];

export const categories = [
  { icon: "🚀", label: "Ciencia Ficción" },
  { icon: "⚔️", label: "Acción" },
  { icon: "🐉", label: "Fantasía" },
  { icon: "👻", label: "Terror" },
  { icon: "🕵️", label: "Thriller" },
  { icon: "💔", label: "Drama" },
  { icon: "😂", label: "Comedia" },
  { icon: "🎭", label: "Crimen" },
  { icon: "📖", label: "Historia" },
  { icon: "🌍", label: "Documental" },
];
